function  WWHBookData_Files(P)
{
P.fA("Using This Help File","preface.html");
P.fA("Conventions Used in This Help File  ","preface2.html");
P.fA("Contacting Technical Support","preface3.html");
P.fA("Using the JDBC Client","usejdbc.html");
P.fA("About the JDBC Client","usejdbc2.html");
P.fA("Registering the JDBC Driver","usejdbc3.html");
P.fA("Specifying JDBC Driver Connection\u00a0URLs","usejdbc4.html");
P.fA("Configuring JDBC Data Sources","usejdbc5.html");
P.fA("Using the Java Transaction API","usejdbc6.html");
P.fA("J2EE Connector Architecture (JCA) Resource Adapter","usejdbc7.html");
P.fA("Specifying Connection Properties","usejdbc8.html");
P.fA("JDBC Connection Properties","usejdbc9.html");
P.fA(" Testing JDBC Connections","usejdbc10.html");
P.fA("Using the JDBC Client on a Java 2 Platform","usejdbc11.html");
P.fA("Using DataDirect Test","jdbctest.html");
P.fA("DataDirect Test Tutorial","jdbctest2.html");
P.fA("Tracking JDBC Calls","spy.html");
P.fA("About DataDirect Spy","spy2.html");
P.fA("Enabling DataDirect Spy","spy3.html");
P.fA("Registering the Spy JDBC Driver","spy4.html");
P.fA("Using Spy with JDBC Data Sources","spy5.html");
P.fA("Checking the DataDirect Spy Version","spy6.html");
P.fA("Developing JDBC Applications","devjdbc.html");
P.fA("JDBC 3.0 Support","devjdbc2.html");
P.fA("JCA Resource Adapter Class","devjdbc3.html");
P.fA("SQL Support","devjdbc4.html");
P.fA("Data Types and Isolation Levels","devjdbc5.html");
P.fA("Threading","devjdbc6.html");
P.fA("Using Scrollable Cursors","devjdbc7.html");
P.fA("Specifying Application IDs","devjdbc8.html");
P.fA("Parameter Metadata Support","devjdbc9.html");
P.fA("ResultSet Metadata Support","devjdbc10.html");
P.fA("Unicode Support","devjdbc11.html");
P.fA("Error Handling","devjdbc12.html");
P.fA("Fine-Tuning JDBC Application Performance","devjdbc13.html");
P.fA("Data Types and Isolation Levels","datatype.html");
P.fA("Supported Data Types","datatype2.html");
P.fA("Informix","datatype3.html");
P.fA("Oracle","datatype4.html");
P.fA("Sybase","datatype5.html");
P.fA("Isolation Levels","datatype6.html");
P.fA("SQL Escape Sequences","scalarfn.html");
P.fA("Date, Time, and Timestamp Escape Sequences","scalarfn2.html");
P.fA("Scalar Functions","scalarfn3.html");
P.fA("Like Predicate Escape Characters","scalarfn4.html");
P.fA("Outer Join Escape Sequences","scalarfn5.html");
P.fA("Procedure Call Escape Sequences","scalarfn6.html");
P.fA("JDBC Support","jdbcsupp.html");
P.fA("Supported Functionality","jdbcsupp2.html");
P.fA("jdbcsupp3.html","jdbcsupp3.html");
P.fA("jdbcsupp4.html","jdbcsupp4.html");
P.fA("jdbcsupp5.html","jdbcsupp5.html");
P.fA("jdbcsupp6.html","jdbcsupp6.html");
P.fA("jdbcsupp7.html","jdbcsupp7.html");
P.fA("jdbcsupp8.html","jdbcsupp8.html");
P.fA("jdbcsupp9.html","jdbcsupp9.html");
P.fA("jdbcsupp10.html","jdbcsupp10.html");
P.fA("jdbcsupp11.html","jdbcsupp11.html");
P.fA("jdbcsupp12.html","jdbcsupp12.html");
P.fA("jdbcsupp13.html","jdbcsupp13.html");
P.fA("jdbcsupp14.html","jdbcsupp14.html");
P.fA("jdbcsupp15.html","jdbcsupp15.html");
P.fA("jdbcsupp16.html","jdbcsupp16.html");
P.fA("jdbcsupp17.html","jdbcsupp17.html");
P.fA("jdbcsupp18.html","jdbcsupp18.html");
P.fA("jdbcsupp19.html","jdbcsupp19.html");
P.fA("jdbcsupp20.html","jdbcsupp20.html");
P.fA("jdbcsupp21.html","jdbcsupp21.html");
P.fA("jdbcsupp22.html","jdbcsupp22.html");
P.fA("jdbcsupp23.html","jdbcsupp23.html");
P.fA("jdbcsupp24.html","jdbcsupp24.html");
P.fA("JDBC Connection Pool Manager","pool.html");
P.fA("Creating a Data Source","pool2.html");
P.fA("Connecting to a Data Source","pool3.html");
P.fA("Terminating the Pool Manager","pool4.html");
P.fA("Troubleshooting Using DataDirect Spy","diagnostics.html");
P.fA("Generating a DataDirect Spy Log ","diagnostics2.html");
}
